[CHALLENGE] 헙크(정현승) 상태 패턴 도전 미션 제출합니다.
HubCreator/java-blackjack pull request #1
Opened 2023-03-12 05:55 UTC by HubCreator

피드백 강의에서도 상태 패턴에 대한 내용이 있어 참고하면서 구현하였습니다. 처음엔 뭔가 `if`문 없이 상태의 전이를 나타낼 수 있어서 대단해보였는데, 결국에 마지막에 가서는 딜러와 플레이어의 결과를 도출하기 위해(서로의 상태를 비교하기 위해) `if`문 사용이 불가피하다는 것을 느꼈습니다. 그렇지만 상태를 계층적으로 나눔으로써 조금 더 중복되는 코드를 줄일 수 있었고, 각 상태마다 할 수 있는 행위와 없는 행위를 명시해줌으로써 더 방어적인 코드가 되었다고 생각합니다.

조금 더 개선할 부분이나 잘못된 부분을 더 알고 싶습니다. 사실 도전 과제를 주시지 않았더라면 그저 이런 패턴이 있구나 하고 실제로 사용해보진 않았을텐데, 완태님 덕분에 조금 더 깊게 공부할 수 있어서 뜻깊었습니다. 감사합니다 :)

2023-03-12 10:33 UTC, wannte requested changes
안녕하세요! 헙크.

몇 가지 피드백 남겼습니다~. 추가 도전 과제라 피드백은 반영은 필수는 아닙니다 :)

2023-03-12 10:33 UTC, wannte commented on src/main/java/domain/state/Ready.java
> +        }
불가능한 case로 보이는데, 혼란을 줄 수 있지 않을까요?

2023-03-12 10:33 UTC, wannte commented on src/main/java/domain/state/Hit.java
> +        }
불가능한 case로 보이는데, 혼란을 줄 수 있지 않을까요?2

2023-03-12 10:33 UTC, wannte commented on src/main/java/domain/state/State.java
> +    }
Blackjack, Bust 객체가 true/false 의 형태로 재정의한 값과 어떤 점이 다를까요?

2023-03-12 10:33 UTC, wannte commented on src/main/java/domain/game/Hand.java
> +    }
state 가 blackjack/bust/stay 의 책임을 가져가게 된 것으로 보이는데요!

Hand는 card의 총합 정도(gamePoint)를 내려주는 역할을 가지고, state 에게 그 책임을 가지게 하는 것은 어떨까요?

2023-03-12 10:33 UTC, wannte commented on src/main/java/domain/game/GamePoint.java
> +    }
이 책임은 이제 Blackjack Bust level 에서 관리되어야 하지 않을까 싶어요

2023-03-12 10:33 UTC, wannte commented on src/main/java/domain/state/Stay.java
> +    }
승,무,패 의 개념이 도메인에서 사라지게 되는 것 같은데요!

승,무,패 를 비교하는 로직은 별도로 두고, 아래의 방법으로 처리하는 것은 어떨까요?

승-> getProfitRate() * bet()
무-> 0
패-> -1 * bet()

2023-03-13 01:38 UTC, HubCreator commented on src/main/java/domain/state/Ready.java
> +        }
넵! 고치겠습니다

2023-03-13 01:38 UTC, HubCreator commented on src/main/java/domain/state/Hit.java
> +        }
넵! 고치겠습니다2 ㅠㅠㅠ

2023-03-13 05:01 UTC, HubCreator commented on src/main/java/domain/state/State.java
> +    }
해당 객체(상태)에서 blackjack인지 bust인지, stay인지 나타내는 메서드가 있다면 해당 상태에서 어떤 상태로의 전이가 가능한지 조금 더 쉽게 알 수 있을 것 같습니다. 하지만 위의 메서드를 각 상태마다 재정의해야 하기 때문에 코드의 중복은 불가피할 것 같습니다.

2023-03-13 05:07 UTC, HubCreator commented on src/main/java/domain/game/Hand.java
> +    }
제가 구현하면서 고민했던 부분은 다음과 같습니다.
버스트인지, 블랙잭인지 결국에는 Hand의 정보가 필요할텐데, 이를 상위의 State에서 관리하는 것이 맞을까? 그렇게 된다면 Hand에게 메시지를 보내서 값을 가져오는 것이 아니라, Hand의 값을 State에서 가져와서 판단하게 되어서 OOP를 만족하지 못하는 것 아닐까?

또 한편으로는 Hand에게 너무 많은 책임을 주기보다, State에서 각 상태에 맞게끔 정보를 반환하는 것이 좋을 것 같다는 생각도 들었습니다.

어떻게 생각하는 것이 조금 더 좋은 방식일지 궁금합니다 ㅎㅎㅎ

2023-03-13 05:17 UTC, HubCreator commented on src/main/java/domain/game/GamePoint.java
> +    }
넵 수정하도록 하겠습니다!

2023-03-13 06:38 UTC, HubCreator commented on src/main/java/domain/state/Stay.java
> +    }
넵 한 번 해보겠습니다!

2023-03-13 11:54 UTC, wannte commented on src/main/java/domain/game/Hand.java
> +    }
기존의 Hand 의 역할이 State 의 역할과 비슷? 겹치는 부분이 있어서 그런 것 같다는 생각이 드네요.

메소드를 사용한기보다는 전파만 하게된다면, 객체를 합치는 시그널로 생각해봐도 좋을 것 같다는 생각을 가지고 있습니다.

2023-03-13 12:02 UTC, wannte commented on src/main/java/domain/result/GameResult.java
> +public enum GameResult {
이러면 어떨까 하는 아이디어 남겨요.

1. GameResult 는 WIN/DRAW/LOSE 의 결과만을 리턴한다. (player가 Bust 인 경우는 Lose입니다)
2. getProfit 은 state 가 책임을 가지고 win 한 경우만 profit 을 더한다?

2023-03-13 12:02 UTC, wannte commented on src/main/java/domain/state/State.java
> +    public abstract boolean isBlackjack();
기본값으로 false 를 정의하고, blackjack 에서만 true로 override 하는 것은 어떨까요?

2023-03-17 08:27 UTC, merged